version: "3.9"

services:
  web:
    build:
      context: ./popcornhub-web   
      dockerfile: Dockerfile
    container_name: popcornhub-web
    ports:
      - "8080:5000"
    environment:
      - API_URL=http://popcornhub-api:5000
    networks:
      - popcornhub_default

networks:
  popcornhub_default:
    external: true