version: "3.9"

services:
  api:
    build: ./popcornhub-api
    container_name: popcornhub-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data

  web:
    build: ./popcornhub-web
    container_name: popcornhub-web
    ports:
      - "8080:5000"
    environment:
      - API_URL=http://api:5000
    depends_on:
      - api