version: "3.9"

services:
  web:
    build: ./popcornhub-web
    container_name: popcornhub-web
    ports:
      - "8080:5000"
    volumes:
      - ./popcornhub-web:/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
